MODEL:
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NO_MARGIN: True
  STRIDE_SIZE: [16, 16]
  BACKBONE: 'ViT-B/16'
  LOSS_TYPE: 'MMC'
  DEPTH_VISION: [9,10,11] 
  DEPTH_TEXT: [9,10,11]
  PROMPT_CSC: False
  TRANSFER_TYPE: "Adapter"
  SAA_LAYER: [12, -1]
  USE_EMA: True
  KERNEL_SIZE: 3
  TEMPERATURE: 2e-3
  OT_REGSC: 0.05

INPUT:
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]
  PROB: 0.5
  RE_PROB: 0.5
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  ENSEMBLE_TYPE: "embedding"
  NUM_GROUPS: 1

DATASETS:
  NAMES: ('COCO_ZS')
  ROOT_DIR: ('/mnt/nas/TrueNas1/COCO')
  NUMBERS: 80

DATALOADER:
  SAMPLER: 'sigmoid'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'AdamW'
  BASE_LR: 5e-5
  IMS_PER_BATCH: 32
  LARGE_FC_LR: False
  LOG_PERIOD: 500
  WEIGHT_DECAY: 1e-4
  MAX_EPOCHS: 6
  EVAL_PERIOD: 3
  SAVE_MODEL: False

TEST:
  EVAL: True
  IMS_PER_BATCH: 512
  RE_RANKING: False
  WEIGHT: ''
  WEIGHT_ITERS: 12800
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './logs/RAM/Natural/COCO'
